version: '3.8'

services:
  spider_backend:
    container_name: spider_backend
    restart: "always"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - 8080
    volumes:
      - "./src/:/app"
    ports:
      - "8080:8080"
